### PR TITLE
Legacy2016

### PR DESCRIPTION
**Pull request by friccita**
Merge conflicts fixed between the pull request with my Rochester corrections and Kak's updates to the photon overlap filter

### CODE REVIEW

**Comment by friccita** [comment]
Can this be merged?

**Comment by albertobelloni** [comment]
Hi Francesca,

GitHub still tells me that there are conflicts to be solved. The “merge pull request” button is greyed out. Frankly, this is what makes me hate git, very awkward system to put together local and remote repositories…
Best,

Alberto

**Comment by friccita** [comment]
I did "git pull upstream legacy2016" to get an indication of the conflicts (my branch name is legacy2016, even though yours is master), and this has apparently caused all my Rochester correction stuff to completely disappear.

**Comment by albertobelloni** [comment]
Hi Francesca,

I just cannot stand git. The command you used seem to, indeed, pull the remote repository content over your local one. I wonder if there is a way to roll back? Best,

Alberto

**Comment by friccita** [comment]
Ok, so I did manage to roll back to the point in time before I did the pull, but now I don't see any merge conflicts...

**Comment by albertobelloni** [comment]
Hi Francesca,

I really do not know how git works, but the usual suggestion is the following: checkout a clean repository in another directory (checkout the branch you want to merge to); replace in that new directory the files you modified; push back the new directory (with the updated files) to remote repository. By construction, there should be no conflicts if you do so. Let me know! Best,

Alberto

**Comment by friccita** [comment]
Something went wrong with this one, so I created another pull request (#93) with the conflicts fixed, and that was merged instead. So this pull request is no longer needed and can be closed.

**Pull request closed without merging**
