### PR TITLE
Fix for Rochester corrections

### PR DESCRIPTION
**Pull request by intrepid42**
image

### CODE REVIEW

**Comment by intrepid42** [comment]
> How did we fix the issue with the spurious rc muon?

By filling the corrected pt only after the muon has been accepted

**Comment by sciencecw** [comment]
/home/kakw/efake/WG_Analysis/Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx: In member function 'void RunModule::FilterMuon(ModuleConfig&)':
/home/kakw/efake/WG_Analysis/Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx:1032:37: error: 'gen_n' is not a member of 'IN'
           for( int gidx = 0; gidx < IN::gen_n; ++gidx ) {
                                     ^
/home/kakw/efake/WG_Analysis/Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx:1033:22: error: 'gen_PID' is not a member of 'IN'
             int id = IN::gen_PID->at(gidx);
                      ^
/home/kakw/efake/WG_Analysis/Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx:1037:22: error: 'gen_status' is not a member of 'IN'
             int st = IN::gen_status->at(gidx);
                      ^
/home/kakw/efake/WG_Analysis/Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx:1042:34: error: 'gen_pt' is not a member of 'IN'
             tleplv.SetPtEtaPhiE( IN::gen_pt->at(gidx),
                                  ^
/home/kakw/efake/WG_Analysis/Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx:1043:34: error: 'gen_eta' is not a member of 'IN'
                                  IN::gen_eta->at(gidx),
                                  ^
/home/kakw/efake/WG_Analysis/Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx:1044:34: error: 'gen_phi' is not a member of 'IN'
                                  IN::gen_phi->at(gidx),
                                  ^
/home/kakw/efake/WG_Analysis/Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx:1045:34: error: 'gen_e' is not a member of 'IN'
                                  IN::gen_e->at(gidx)
                                  ^

**Comment by sciencecw** [comment]
Definition is missing on include/ ?

**Comment by sciencecw** [comment]
It's missing a #ifdef EXISTS_gen_n for data

**Comment by intrepid42** [comment]
Ok, but why is any data event running into the `else` block after `if( OUT::isData) {`?

**Pull request merged**
