### PR TITLE
Legacy2016

### PR DESCRIPTION
**Pull request by friccita**
- Rochester corrections added to ApplyScaleFactors module
- first attempt at fixing FilterOverlap to remove gen photons properly; to be tested/debugged when ntuples are available with gen photon info saved

### CODE REVIEW

**Comment by friccita** [comment]
can this be merged?

**Comment by friccita** [comment]
(or have I pushed to the wrong branch -- should it be master instead of legacy2016?)

**Comment by yongbinfeng** [comment]
I don't know what others think, but I feel it might be better to merge to master, since everything is on master now.

**Comment by friccita** [comment]
I do agree, I should merge to master; it was a mistake on my part. I'll close this pull request and try to push to master instead...

**Pull request closed without merging**
