### PR TITLE
FilterOverlap update

### PR DESCRIPTION
**Pull request by sciencecw**
remote default abs(eta) and dr cut in FilterOverlap
clean auto-generated header files at every module
remove mt_res blinding cut in 2018
condor description update

### CODE REVIEW

**Comment by sciencecw** [comment]
piecing together WG photon-pT-bin samples: we used to require no generator photons outsides of cut range, but this removes also events where the leading photon falls under the range, but includes another sub-leading gen photon outside of range, which leads to removal of the event. A new cut is implemented to cut on the leading gen photon.

lingering problem: ~1% events are without any gen IsPromptFS photons and we are unsure what to do with them.

Original cut: `FilterPhoton : cut_genph_isPromptFS [ == True ] ; cut_genph_pt [ < 180 | > 550 ] ; cut_n_gen_phot [ == 0] ; `

New cut: `FilterPhoton : cut_genph_isPromptFS [ == True ] ; cut_genph_pt [ > 10 ] ; cut_lead_genph_pt [ > 180 && < 550 ] ; cut_n_gen_phot [ > 0] ; `
image
[http://hepcms-hn.umd.edu/~kakw/Plots/MakeWGPhCutValidPlot/view.php](url)

**Comment by sciencecw** [comment]
Shared object .so files are linked to standard libraries and needs to be present for executable to run. Object .o files are static and can be cleaned after each compilation.

> [kakw@hepcms-in2 FilterOverlap]$ ldd obj/RunAnalysis_MC_olap_LepGamma_elg.exe/cintLib.so 
> 	linux-vdso.so.1 =>  (0x00007ffd89594000)
> 	libstdc++.so.6 => /cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/gcc/5.3.0/lib64/libstdc++.so.6 (0x00007f3b6d95b000)
> 	libm.so.6 => /lib64/libm.so.6 (0x00007f3b6d6bf000)
> 	libgcc_s.so.1 => /cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/gcc/5.3.0/lib64/libgcc_s.so.1 (0x00007f3b6d6a8000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3b6d48b000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007f3b6d0f6000)
> 	librt.so.1 => /lib64/librt.so.1 (0x00007f3b6ceee000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000003dbc000000)

**Comment by albertobelloni** [comment]
Hi Kak, there seems to be a conflict to resolve!

**Comment by albertobelloni** [comment]
I suspect the conflict arose with a recent update (did both you and Markus update lists of samples?)

**Pull request merged**
